--Review table

SELECT * FROM crimedata
LIMIT 10

--Creating copy of table:

CREATE TABLE crimedata_cleaned
(LIKE crimedata);

INSERT INTO crimedata_cleaned
SELECT * FROM crimedata;

SELECT * FROM crimedata_cleaned
LIMIT 10;

---
--Checking for duplicate rows:

WITH crimedata_dupcheck AS (
	SELECT *, 
		ROW_NUMBER() OVER (PARTITION BY "DATETIME", "CASENUMBER", "DESCRIPTION", "Location") AS ROW_NUM
	FROM crimedata)
SELECT * FROM crimedata_dupcheck
WHERE ROW_NUM >1;

---

--Data wrangling: 

--Replacing null values in CRIMETYPE:

----Vehicle-related theft charges:

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'VEHICLE THEFT'
WHERE "CRIMETYPE" = 'STOLEN VEHICLE';

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE ("DESCRIPTION" LIKE '%THEFT%' OR "DESCRIPTION" LIKE '%STOLEN%') 
	AND ("DESCRIPTION" LIKE '%AUTO%' OR "DESCRIPTION" LIKE '%VEH%');

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'VEHICLE THEFT'
WHERE ("DESCRIPTION" LIKE '%THEFT%' OR "DESCRIPTION" LIKE '%STOLEN%') 
	AND ("DESCRIPTION" LIKE '%AUTO%' OR "DESCRIPTION" LIKE '%VEH%');

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%CARJACKING%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'VEHICLE ROBBERY'
WHERE "DESCRIPTION" LIKE '%CARJACKING%';

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%BURGLARY%' 
	AND ("DESCRIPTION" LIKE '%AUTO%' OR "DESCRIPTION" LIKE '%VEH%');

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'VEHICLE BURGLARY'
WHERE "DESCRIPTION" LIKE '%BURGLARY%' 
	AND ("DESCRIPTION" LIKE '%AUTO%' OR "DESCRIPTION" LIKE '%VEH%');

----General theft charges:

------(Lumping together theft-related charges e.g. non-vehicle grand theft, petty theft, etc. )

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%THEFT%' AND "DESCRIPTION" NOT LIKE '%AUTO%' 
	AND "DESCRIPTION" NOT LIKE '%VEH%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'THEFT'
WHERE "DESCRIPTION" LIKE '%THEFT%' AND "DESCRIPTION" NOT LIKE '%AUTO%' 
	AND "DESCRIPTION" NOT LIKE '%VEH%';

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%ROBBERY%' AND "DESCRIPTION" NOT LIKE '%AUTO%' 
	AND "DESCRIPTION" NOT LIKE '%VEH%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'ROBBERY'
WHERE "DESCRIPTION" LIKE '%ROBBERY%' AND "DESCRIPTION" NOT LIKE '%AUTO%' 
	AND "DESCRIPTION" NOT LIKE '%VEH%';

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%BURGLARY%' AND "DESCRIPTION" NOT LIKE '%AUTO%' 
	AND "DESCRIPTION" NOT LIKE '%VEH%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'BURGLARY'
WHERE "DESCRIPTION" LIKE '%BURGLARY%' AND "DESCRIPTION" NOT LIKE '%AUTO%' 
	AND "DESCRIPTION" NOT LIKE '%VEH%';

----Other crimes

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%DUI%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'DUI'
WHERE "DESCRIPTION" LIKE '%DUI%';

--
------(Lumping together assault & battery, excluding sex offenses)
SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%ASSAULT%' OR "DESCRIPTION" LIKE '%BATTERY%' 
	OR "DESCRIPTION" LIKE '%ADW%' AND "DESCRIPTION" NOT LIKE '%SEX%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'ASSAULT / BATTERY - NON-SEXUAL'
WHERE "DESCRIPTION" LIKE '%ASSAULT%' OR "DESCRIPTION" LIKE '%BATTERY%' 
	OR "DESCRIPTION" LIKE '%ADW%' AND "DESCRIPTION" NOT LIKE '%SEX%';

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%RAPE%' OR "DESCRIPTION" LIKE '%SEX%' 
	OR "DESCRIPTION" LIKE '%SODOMY%' OR "DESCRIPTION" LIKE '%COPULATION%' 
	OR "DESCRIPTION" LIKE '%INDECENT%' OR "DESCRIPTION" LIKE '%MOLEST%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'RAPE / SEX OFFENSES'
WHERE "DESCRIPTION" LIKE '%RAPE%' OR "DESCRIPTION" LIKE '%SEX%' 
	OR "DESCRIPTION" LIKE '%SODOMY%' OR "DESCRIPTION" LIKE '%COPULATION%' 
	OR "DESCRIPTION" LIKE '%INDECENT%' OR "DESCRIPTION" LIKE '%MOLEST%';
	
--
------(Lumping together court-related charges e.g. contempt, violated court orders, etc.)
SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%COURT%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'COURT-RELATED'
WHERE "DESCRIPTION" LIKE '%COURT%';

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%VANDALISM%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'VANDALISM'
WHERE "DESCRIPTION" LIKE '%VANDALISM%';

--
------(Lumping together disorderly conduct and disturbing the peace, excluding prostitution to its own category)

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%DISORDERLY%' OR "DESCRIPTION" LIKE '%DISTURB%' 
	OR "DESCRIPTION" LIKE '%OFFENSIVE WORDS%'
	AND "DESCRIPTION" NOT LIKE '%PROST%' AND "DESCRIPTION" NOT LIKE '%COURT%';
	
UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'DISORDERLY CONDUCT/DISTURBING PEACE'
WHERE ("DESCRIPTION" LIKE '%DISORDERLY%' OR "DESCRIPTION" LIKE '%DISTURB%'
	OR ("DESCRIPTION" LIKE '%OFFENSIVE WORDS%' AND "CRIMETYPE" IS NULL)) 
	AND "DESCRIPTION" NOT LIKE '%PROST%' AND "DESCRIPTION" NOT LIKE '%COURT%';
	

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%PROST%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'PROSTITUTION'
WHERE "DESCRIPTION" LIKE '%PROST%';

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE ("DESCRIPTION" LIKE '%WEAPON%' AND "CRIMETYPE" IS NULL) 
	OR "DESCRIPTION" LIKE '%AMMUNITION%' OR "DESCRIPTION" LIKE '%MFG%'; 

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'WEAPONS'
WHERE ("DESCRIPTION" LIKE '%WEAPON%' AND "CRIMETYPE" IS NULL) 
	OR "DESCRIPTION" LIKE '%AMMUNITION%' OR "DESCRIPTION" LIKE '%MFG%'; 

--
------(Lumping all firearm charges that were not already accounted for above e.g. battery, robbery, etc.)

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%FIREARM%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'FIREARM'
WHERE ("DESCRIPTION" LIKE '%FIREARM%' OR 
	   "DESCRIPTION" LIKE '%SHOOT%' OR "DESCRIPTION" LIKE '%HANDGUN%') 
	   AND "CRIMETYPE" IS NULL;

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%THREAT%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'THREATS'
WHERE "DESCRIPTION" LIKE '%THREAT%';

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%ARSON%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'ARSON'
WHERE "DESCRIPTION" LIKE '%ARSON%' OR "DESCRIPTION" LIKE '%FIRE %';

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%IDENTIFICATION%' AND "DESCRIPTION" NOT LIKE '%FIREARM%' 
	AND "DESCRIPTION" NOT LIKE '%VEHICLE%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'FRAUD'
WHERE "DESCRIPTION" LIKE '%IDENTIFICATION%' AND "DESCRIPTION" NOT LIKE '%FIREARM%' 
	AND "DESCRIPTION" NOT LIKE '%VEHICLE%';

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%FICTITIOUS%' OR "DESCRIPTION" LIKE '%FORGE%';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'FORGERY / COUNTERFEITING'
WHERE "DESCRIPTION" LIKE '%FICTITIOUS%' OR "DESCRIPTION" LIKE '%FORGE%';

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%NARCOTIC%' OR 
	("DESCRIPTION" IS NULL AND ("DESCRIPTION" LIKE '%SUBSTANCE%' OR "DESCRIPTION" LIKE '%PARAPHERNALIA%' 
	OR "DESCRIPTION" LIKE '%SUBSTANCE%' OR "DESCRIPTION" LIKE '%OPIUM%' OR "DESCRIPTION" LIKE '%MARIJUANA%'
	OR "DESCRIPTION" LIKE '%METHAMPHETAMINE%' OR "DESCRIPTION" LIKE '%MUSHROOM%'));

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'NARCOTICS'
WHERE "DESCRIPTION" LIKE '%NARCOTIC%' OR 
	("CRIMETYPE" IS NULL AND ("DESCRIPTION" LIKE '%SUBSTANCE%' OR "DESCRIPTION" LIKE '%PARAPHERNALIA%' 
	OR "DESCRIPTION" LIKE '%SUBSTANCE%' OR "DESCRIPTION" LIKE '%OPIUM%' OR "DESCRIPTION" LIKE '%MARIJUANA%'
	OR "DESCRIPTION" LIKE '%METHAMPHETAMINE%' OR "DESCRIPTION" LIKE '%MUSHROOM%'));

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%UNEXPLAINED%' OR "DESCRIPTION" LIKE 'MURDER';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'HOMICIDE / UNEXPLAINED DEATH'
WHERE "DESCRIPTION" LIKE '%UNEXPLAINED%' OR "DESCRIPTION" LIKE 'MURDER';

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%CRPL%' OR "DESCRIPTION" LIKE '%CORPORAL%'
	OR "DESCRIPTION" LIKE '%CRUELTY%'; 

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'DOMESTIC VIOLENCE'
WHERE "DESCRIPTION" LIKE '%CRPL%' OR "DESCRIPTION" LIKE '%CORPORAL%'
	OR "DESCRIPTION" LIKE '%CRUELTY%'; 

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%KIDNAP%'; 

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'KIDNAPPING'
WHERE "DESCRIPTION" LIKE '%KIDNAP%'; 

--

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "DESCRIPTION" LIKE '%TAX%';; 

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'TAX EVASION'
WHERE "DESCRIPTION" LIKE '%TAX%' 

--
------(Lumping all remaining unassigned charges to "OTHER" crime type)

SELECT "CRIMETYPE", "DESCRIPTION" FROM crimedata_cleaned
WHERE "CRIMETYPE" IS NULL;

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'OTHER'
WHERE "CRIMETYPE" IS NULL;

---

--Merging crime types:

SELECT "CRIMETYPE", COUNT("CASENUMBER") CRIMECOUNT FROM crimedata_cleaned
GROUP BY "CRIMETYPE" 
ORDER BY "CRIMETYPE";

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'VEHICLE BURGLARY'
WHERE "CRIMETYPE" = 'BURG - AUTO';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'BURGLARY'
WHERE "CRIMETYPE" LIKE 'BURG %';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'DISORDERLY CONDUCT/DISTURBING PEACE'
WHERE "CRIMETYPE" = 'DISORDERLY CONDUCT';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'ASSAULT / BATTERY - NON-SEXUAL'
WHERE "CRIMETYPE" = 'FELONY ASSAULT' OR "CRIMETYPE" = 'MISDEMEANOR ASSAULT';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'RAPE / SEX OFFENSES'
WHERE "CRIMETYPE" = 'FORCIBLE RAPE' OR "CRIMETYPE" = 'OTHER SEX OFFENSES';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'FORGERY / COUNTERFEITING'
WHERE "CRIMETYPE" = 'FORGERY & COUNTERFEITING';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'HOMICIDE / UNEXPLAINED DEATH'
WHERE "CRIMETYPE" = 'HOMICIDE';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'THEFT'
WHERE "CRIMETYPE" = 'GRAND THEFT' OR "CRIMETYPE" = 'PETTY THEFT' 
	OR "CRIMETYPE" = 'POSSESSION - STOLEN PROPERTY';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'VEHICLE THEFT'
WHERE "CRIMETYPE" = 'RECOVERED O/S STOLEN' OR "CRIMETYPE" = 'RECOVERED VEHICLE - OAKLAND STOLEN' 
	OR "CRIMETYPE" = 'STOLEN AND RECOVERED VEHICLE';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'OTHER'
WHERE "CRIMETYPE" = 'MISCELLANEOUS TRAFFIC CRIME';

UPDATE crimedata_cleaned
SET "CRIMETYPE" = 'FIREARM'
WHERE "CRIMETYPE" = 'BRANDISHING';

---
--Exploring breakdown of crime per crime type:

SELECT "CRIMETYPE", COUNT("CASENUMBER") CRIMECOUNT FROM crimedata_cleaned
GROUP BY "CRIMETYPE" 
ORDER BY CRIMECOUNT DESC;

---
--Separating location into latitude and longitude columns

ALTER TABLE crimedata_cleaned
ADD COLUMN "LATITUDE" character varying,
ADD COLUMN "LONGITUDE" character varying;

UPDATE crimedata_cleaned
SET "LATITUDE" = 
	SUBSTRING(SPLIT_PART("Location", SPLIT_PART("Location", ' ',2),2), 
	1, 
	LENGTH(SPLIT_PART("Location", SPLIT_PART("Location", ' ',2),2))-1);
	
UPDATE crimedata_cleaned
SET "LONGITUDE" = SUBSTRING(SPLIT_PART("Location", ' ', 2), 2);

ALTER TABLE crimedata_cleaned
DROP COLUMN "Location";

---
--Copying cleaned data table to CSV file

COPY crimedata_cleaned TO 'C:\Users\ivan\Documents\data portfolio\Oakland crime\crimedata_cleaned.csv' DELIMITER ',' CSV HEADER;

---

